# Generated by Django 6.0.5 on 2026-05-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('sale', 'Sale Revenue'), ('sale_payment', 'Customer Payment Received'), ('purchase', 'Stock Purchase'), ('supplier_payment', 'Supplier Payment Made'), ('expense', 'Business Expense')], max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('inflow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outflow', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('sale_id', models.PositiveIntegerField(blank=True, null=True)),
                ('purchase_id', models.PositiveIntegerField(blank=True, null=True)),
                ('expense_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
